### ISSUE TITLE
Error and fix to use a Picamera V2 instead of V3

### ISSUE THREAD

**Issue by mharmuth** [AndreaFavero71/timelapse#1]
First of all: Thank you for this great project!

I got a little error when trying to execute the script. I've got a Raspberry Pi4 Model B with the Pi camera module V2. 
`python3-pycamera2` is installed and working (I tested it with an example script from the project).

But when I try to run your script, I get the following log
```
pi@pios:~/timelapse $ python3 timelapse.py

Processor architecture: aarch64

[1:17:28.995680973] [5916]  INFO Camera camera_manager.cpp:313 libcamera v0.3.0+65-6ddd79b5
[1:17:29.021947286] [5919]  WARN RPiSdn sdn.cpp:40 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[1:17:29.023584068] [5919]  WARN RPI vc4.cpp:392 Mismatch between Unicam and CamHelper for embedded data usage!
[1:17:29.024210767] [5919]  INFO RPI vc4.cpp:446 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media4 and ISP device /dev/media1
[1:17:29.024254303] [5919]  INFO RPI pipeline_base.cpp:1104 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[1:17:29.026548765] [5916]  INFO Camera camera_manager.cpp:313 libcamera v0.3.0+65-6ddd79b5
[1:17:29.051271480] [5922]  WARN RPiSdn sdn.cpp:40 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[1:17:29.052839967] [5922]  WARN RPI vc4.cpp:392 Mismatch between Unicam and CamHelper for embedded data usage!
[1:17:29.053406703] [5922]  INFO RPI vc4.cpp:446 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media4 and ISP device /dev/media1
[1:17:29.053443869] [5922]  INFO RPI pipeline_base.cpp:1104 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[1:17:29.060032979] [5916]  INFO Camera camera.cpp:1183 configuring streams: (0) 1920x1080-XBGR8888 (1) 640x360-YUV420 (2) 1920x1080-SRGGB10_CSI2P
[1:17:29.060428680] [5922]  INFO RPI vc4.cpp:621 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected sensor format: 1920x1080-SRGGB10_1X10 - Selected unicam format: 1920x1080-pRAA
unknown control 'wide_dynamic_range'
  HDR setting returned an error

Failing to close the Picamera
Failing to clean the display
Failing to set low the GPIO pin 22
Traceback (most recent call last):
  File "/home/pi/timelapse/timelapse.py", line 1183, in <module>
    variables, error = setup()             # retrieves settings, and initializes things
                       ^^^^^^^
  File "/home/pi/timelapse/timelapse.py", line 256, in setup
    picam2, camera_started, error = set_camera(camera_w, camera_h, rotate_180, hdr, autofocus, focus_dist_m, preview)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable float object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/timelapse/timelapse.py", line 1185, in <module>
    exit_func(error)                       # exit function is caleld
    ^^^^^^^^^^^^^^^^
  File "/home/pi/timelapse/timelapse.py", line 1134, in exit_func
    if display:
       ^^^^^^^
NameError: name 'display' is not defined
```

Here is my `settings.txt`: 
[settings.txt](https://github.com/user-attachments/files/16202125/settings.txt)

I don't know what the error can be. Maybe you can help ;-)

**Comment by AndreaFavero71** [comment]
This code has been writtren for the Picamera V3.
The camera V2 does't have some of features of the V3 model, like autofocus and HDR, and errors are generated when trying to set the parameters for those features.

A possible fix:
1) at timelapse.py comment out rows from 334 to 349 included.
```
    picam2.configure(camera_conf)                     # applying settings to the camera
    
#     if hdr:                                       # case hdr is set True
#         ret = os.system(f"v4l2-ctl --set-ctrl wide_dynamic_range=1 -d /dev/v4l-subdev0") # hdr on
#     else:                                         # case hdr is set False
#         ret = os.system(f"v4l2-ctl --set-ctrl wide_dynamic_range=0 -d /dev/v4l-subdev0") # hdr off
#     if ret != 0:                                  # case setting the hdr does not return zero
#         print("  HDR setting returned an error")  # feedback is printed to the terminal
#         error = 0.5                               # error variable is set to 1
#         return error                              # error code is returned
#     else:                                         # case setting the hdr returns zero
#         sleep(0.5)                                # little sleep time    
#     
#     if autofocus:                                 # case autofocus is set True
#         picam2.set_controls({"AfMode": controls.AfModeEnum.Auto})  # Autofocus Auto requires a trigger to execute the focus
#     else:                                         # case autofocus is set False
#         focus_dist = 1/focus_dist_m if focus_dist_m > 0 else 10    #preventing zero division; 0.1 meter is the min focus dist (1/0.1=10)
#         picam2.set_controls({"AfMode": controls.AfModeEnum.Manual, "LensPosition": focus_dist}) # manual focus; 0.0 is infinite (1/>>), 2 is 50cm (1/0.5)
    
    if preview:                                       # case the previes is set True
        picam2.start_preview(Preview.QTGL)            # preview related function is activated
    else:                                             # case the previes is set False
        picam2.start_preview(Preview.NULL)            # preview related function is set Null
```
2) set false the parameters autofocus and HDR in the settings.txt (as per yourr current settings).
.... and the script will be compatible with the V2 camera (I have just tried).

Please be aware:
1) the PiCamera V2 has fix focus, that can only be manually adjusted.
2) the HDR is really a worth feature, especially when the subject is partially shadowed.
Of course it depends from your application, if the autofocus (that also means you can set a fix focus to a given distance via the settings) and the HDR are usefull or not.

**Comment by mharmuth** [comment]
Hi @AndreaFavero71,

thanks for your help. I can confirm that it's working with the rows commented out. Thanks again!

But I will go and grab the PiCamera V3 to have the additional features.
